

export interface IDestinos {
    IataCode:        string;
    OriginCode:      string;
    Origin:          string;
    DestinationCode: string;
    Destination:     string;
    Rate:            number;
    Tax:             number;
    Total:           number;
    DateStart:       string;
    DateEnd:         string;
    SearchTime:      string;
}

export const mockedDestinos = {
  Result: [
    {
      IataCode: '',
      OriginCode: 'LIM',
      Origin: 'LIMA',
      DestinationCode: 'MIA',
      Destination: 'MIAMI',
      Rate: 97,
      Tax: 152.72,
      Total: 250,
      DateStart: '20/06/2022',
      DateEnd: '24/06/2022',
      SearchTime: 'hace 34 min.',
    },
    {
      IataCode: '',
      OriginCode: 'LIM',
      Origin: 'LIMA',
      DestinationCode: 'MIA',
      Destination: 'MIAMI',
      Rate: 97,
      Tax: 152.72,
      Total: 250,
      DateStart: '27/06/2022',
      DateEnd: '11/07/2022',
      SearchTime: 'hace 34 min.',
    },
    {
      IataCode: '',
      OriginCode: 'LIM',
      Origin: 'LIMA',
      DestinationCode: 'MIA',
      Destination: 'MIAMI',
      Rate: 154,
      Tax: 138.08,
      Total: 293,
      DateStart: '14/03/2022',
      DateEnd: '26/03/2022',
      SearchTime: 'hace 41 min.',
    },
    {
      IataCode: '',
      OriginCode: 'LIM',
      Origin: 'LIMA',
      DestinationCode: 'MIA',
      Destination: 'MIAMI',
      Rate: 154,
      Tax: 138.08,
      Total: 293,
      DateStart: '24/03/2022',
      DateEnd: '29/03/2022',
      SearchTime: 'hace 1 hora',
    },
    {
      IataCode: '',
      OriginCode: 'LIM',
      Origin: 'LIMA',
      DestinationCode: 'MIA',
      Destination: 'MIAMI',
      Rate: 154,
      Tax: 138.08,
      Total: 293,
      DateStart: '27/02/2022',
      DateEnd: '08/03/2022',
      SearchTime: 'hace 3 horas',
    },
    {
      IataCode: '',
      OriginCode: 'LIM',
      Origin: 'LIMA',
      DestinationCode: 'MIA',
      Destination: 'MIAMI',
      Rate: 154,
      Tax: 138.08,
      Total: 293,
      DateStart: '23/03/2022',
      DateEnd: '29/03/2022',
      SearchTime: 'hace 3 horas',
    },
    {
      IataCode: '',
      OriginCode: 'LIM',
      Origin: 'LIMA',
      DestinationCode: 'MIA',
      Destination: 'MIAMI',
      Rate: 154,
      Tax: 138.08,
      Total: 293,
      DateStart: '20/04/2022',
      DateEnd: '27/04/2022',
      SearchTime: 'hace 4 horas',
    },
    {
      IataCode: '',
      OriginCode: 'LIM',
      Origin: 'LIMA',
      DestinationCode: 'MIA',
      Destination: 'MIAMI',
      Rate: 154,
      Tax: 138.08,
      Total: 293,
      DateStart: '18/02/2022',
      DateEnd: '23/02/2022',
      SearchTime: 'hace 4 horas',
    },
    {
      IataCode: '',
      OriginCode: 'LIM',
      Origin: 'LIMA',
      DestinationCode: 'MIA',
      Destination: 'MIAMI',
      Rate: 154,
      Tax: 138.08,
      Total: 293,
      DateStart: '21/04/2022',
      DateEnd: '30/04/2022',
      SearchTime: 'hace 5 horas',
    },
    {
      IataCode: '',
      OriginCode: 'LIM',
      Origin: 'LIMA',
      DestinationCode: 'MIA',
      Destination: 'MIAMI',
      Rate: 154,
      Tax: 138.08,
      Total: 293,
      DateStart: '22/04/2022',
      DateEnd: '30/04/2022',
      SearchTime: 'hace 5 horas',
    },
  ],
  TrackingCode: '1',
  State: { Ok: true },
};