export const MockedInfoAerolineas =  {
    CountryCode: 'PE',
    Country: 'Peru',
    Items: [
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'ANS',
        Destination: 'Andahuaylas',
        Rate: 205,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'AQP',
        Destination: 'Arequipa',
        Rate: 53,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'ATG',
        Destination: 'Atalaya',
        Rate: 236,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'AYP',
        Destination: 'Ayacucho',
        Rate: 52,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'CJA',
        Destination: 'Cajamarca',
        Rate: 52,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'CIX',
        Destination: 'Chiclayo',
        Rate: 53,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'CUZ',
        Destination: 'Cusco',
        Rate: 48,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'HUU',
        Destination: 'Huanuco',
        Rate: 115,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'ATA',
        Destination: 'Huaraz',
        Rate: 273,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'IQT',
        Destination: 'Iquitos',
        Rate: 55,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'JAU',
        Destination: 'Jauja',
        Rate: 43,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'JUL',
        Destination: 'Juliaca',
        Rate: 54,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'MZA',
        Destination: 'Mazamari',
        Rate: 148,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'PIU',
        Destination: 'Piura',
        Rate: 41,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'PEM',
        Destination: 'Pto. Maldonado',
        Rate: 50,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'PCL',
        Destination: 'Pucallpa',
        Rate: 57,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'TCQ',
        Destination: 'Tacna',
        Rate: 61,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'TYL',
        Destination: 'Talara',
        Rate: 59,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'TPP',
        Destination: 'Tarapoto',
        Rate: 57,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'TGI',
        Destination: 'Tingo Maria',
        Rate: 111,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'TRU',
        Destination: 'Trujillo',
        Rate: 59,
      },
      {
        ContinentCode: 'SA',
        Continent: 'SUDAMERICA',
        DestinationCode: 'TBP',
        Destination: 'Tumbes',
        Rate: 59,
      },
    ],
  }
