export const MockedTabVuelos = [
    {
        "destination_id": 584,
        "city": "Madrid (Todos Los Aeropuertos)",
        "country": "España",
        "country_id": "ES",
        "state": "\\N",
        "state_id": "\\N",
        "language_id": "es",
        "aerocodiata": "MAD",
        "tn_iata_padre": "0",
        "tipo_busqueda": "AEROPUERTOS",
        "city_code": "MAD"
    },
    {
        "destination_id": 657,
        "city": "Madison",
        "country": "Estados Unidos",
        "country_id": "US",
        "state": "WI",
        "state_id": "\\N",
        "language_id": "es",
        "aerocodiata": "MSN",
        "tn_iata_padre": "0",
        "tipo_busqueda": "AEROPUERTOS",
        "city_code": "MSN"
    },
    {
        "destination_id": 1004,
        "city": "Antananarivo",
        "country": "Madagascar",
        "country_id": "MG",
        "state": "\\N",
        "state_id": "\\N",
        "language_id": "es",
        "aerocodiata": "TNR",
        "tn_iata_padre": "0",
        "tipo_busqueda": "AEROPUERTOS",
        "city_code": "TNR"
    },
    {
        "destination_id": 643,
        "city": "Morondava",
        "country": "Madagascar",
        "country_id": "MG",
        "state": "\\N",
        "state_id": "\\N",
        "language_id": "es",
        "aerocodiata": "MOQ",
        "tn_iata_padre": "0",
        "tipo_busqueda": "AEROPUERTOS",
        "city_code": "MOQ"
    },
    {
        "destination_id": 587,
        "city": "madang",
        "country": "Papúa Nueva Guinea (Niugini)",
        "country_id": "PG",
        "state": "\\N",
        "state_id": "\\N",
        "language_id": "es",
        "aerocodiata": "MAG",
        "tn_iata_padre": "0",
        "tipo_busqueda": "AEROPUERTOS",
        "city_code": "MAG"
    },
    {
        "destination_id": 585,
        "city": "Madrid - Atocha St.",
        "country": "España",
        "country_id": "ES",
        "state": "\\N",
        "state_id": "\\N",
        "language_id": "es",
        "aerocodiata": "MAD",
        "tn_iata_padre": "2",
        "tipo_busqueda": "AEROPUERTOS",
        "city_code": "XOC"
    }
]